using System.Globalization;
using System.Text;
using Casazen.Core.Entities;
using Casazen.Core.Entities.Enums;
using Casazen.Core.Regulatory;

namespace Casazen.Infrastructure.Services;

/// <summary>
/// Versioned prompt of the SEO pages (SE-01, A8-06): instructions on language, allowed HTML (the FD-15 allowlist of
/// <see cref="SeoHtmlSanitizer"/>), structure and length, then the only facts and sources the text may use. The output
/// is checked by <see cref="SeoGeneratedContent"/> and stored as a draft: it is published only after a human review.
/// Change <see cref="Version"/> whenever the text below changes: the version is stored with each revision, and pages
/// generated with another version are regenerated by the next "Genera" even when their data did not change.
/// </summary>
public static class SeoContentPrompt
{
    public const string Version = "seo-it-2026-09-v1";

    private static readonly CultureInfo Italian = CultureInfo.GetCultureInfo("it-IT");

    /// <summary>
    /// Verified facts with their official sources, from <c>.claude/context/regulations/cin.md</c> (RS-2) and
    /// <c>alloggiati.md</c> (RS-1). Never add a fact here without an official source verified there.
    /// </summary>
    private static readonly string[] ComplianceFacts =
    [
        "CIN: il Codice Identificativo Nazionale è obbligatorio per le unità immobiliari destinate a locazione breve o " +
        "turistica (D.L. 145/2023, art. 13-ter). Si ottiene sulla Banca Dati delle Strutture Ricettive (BDSR) del " +
        "Ministero del Turismo, va esposto all'esterno dell'immobile e indicato in ogni annuncio.",
        "Alloggiati Web: chi dà alloggio comunica le generalità degli ospiti alla Questura tramite il portale Alloggiati " +
        "Web entro 24 ore dall'arrivo, ed entro 6 ore dall'arrivo se il soggiorno non supera le 24 ore (art. 109 TULPS).",
    ];

    private static readonly (string Label, string Url)[] ComplianceSources =
    [
        ("D.L. 145/2023, art. 13-ter (Normattiva)",
            "https://www.normattiva.it/uri-res/N2Ls?urn%3Anir%3Astato%3Adecreto.legge%3A2023-10-18%3B145%7Eart13ter="),
        ("Banca Dati delle Strutture Ricettive (Ministero del Turismo)",
            "https://www.ministeroturismo.gov.it/banca-dati-strutture-ricettive/"),
        ("Portale Alloggiati Web (Polizia di Stato)", "https://alloggiatiweb.poliziadistato.it"),
        ("Art. 109 TULPS (testo pubblicato sul portale Alloggiati Web)",
            "https://alloggiatiweb.poliziadistato.it/PortaleAlloggiati/Download/Normativa/109_TULPS.pdf"),
    ];

    public static string Build(ComuneInfo comune, SeoPageType pageType, IReadOnlyList<TouristTaxRate> taxRates)
    {
        var isGuide = pageType == SeoPageType.ComplianceGuide;
        var sb = new StringBuilder();

        sb.AppendLine("Sei un redattore di CasaZen, un software per host di affitti brevi. Scrivi il testo di una pagina web informativa.");
        sb.AppendLine();
        sb.AppendLine("ISTRUZIONI");
        sb.AppendLine($"1. Lingua: italiano chiaro e neutro, rivolto agli host di affitti brevi del comune di {comune.Name}.");
        sb.AppendLine("2. Formato: rispondi solo con un frammento HTML, senza testo prima o dopo, senza markdown e senza blocchi di codice. " +
                      "Tag ammessi: <h2>, <h3>, <p>, <ul>, <ol>, <li>, <strong>, <em>, <a href=\"https://...\">, <table>, <thead>, <tbody>, <tr>, <th>, <td>, <br>. " +
                      "Nessun altro tag, nessun attributo diverso da href, niente <h1> (il titolo della pagina esiste già), niente stili, script o immagini.");
        sb.AppendLine("3. Struttura: queste sezioni <h2>, in quest'ordine, ciascuna con almeno un paragrafo <p> o un elenco:");
        foreach (var section in Sections(comune, isGuide))
            sb.AppendLine($"   - <h2>{section}</h2>");
        sb.AppendLine("   Nella sezione \"Fonti ufficiali\" metti un elenco <ul> con un link <a> per ciascuna delle FONTI, con l'URL esatto.");
        sb.AppendLine("4. Contenuti: usa solo i FATTI e i DATI elencati sotto. Non inventare importi, date, scadenze, sanzioni, norme, " +
                      "procedure o nomi di uffici. Se un dato manca, scrivi che non è disponibile e rimanda alle fonti ufficiali.");
        sb.AppendLine("5. Fonti: cita e collega solo le FONTI elencate sotto. Non citare altre leggi, siti, enti, recensioni o classifiche " +
                      "e non affermare di aver consultato fonti diverse da queste.");
        sb.AppendLine("6. Non dare consulenza legale o fiscale personalizzata e non promettere risultati: ricorda che le regole possono " +
                      "cambiare e vanno verificate sulle fonti ufficiali.");
        sb.AppendLine("7. Lunghezza: tra 300 e 600 parole.");
        sb.AppendLine();
        sb.AppendLine("DATI");
        sb.AppendLine($"Comune: {comune.Name} (codice ISTAT {comune.Code})");
        sb.AppendLine(isGuide
            ? "Pagina: guida agli adempimenti per gli affitti brevi nel comune"
            : "Pagina: imposta di soggiorno del comune per gli affitti brevi");
        sb.AppendLine();
        sb.AppendLine("FATTI");
        if (isGuide)
        {
            foreach (var fact in ComplianceFacts)
                sb.AppendLine($"- {fact}");
        }

        AppendTouristTax(sb, comune, taxRates);
        sb.AppendLine();
        sb.AppendLine("FONTI");
        var sources = Sources(isGuide, taxRates).ToList();
        if (sources.Count == 0)
            sb.AppendLine("- Nessuna fonte disponibile: nella sezione \"Fonti ufficiali\" scrivi di consultare il sito istituzionale del comune, senza link.");
        foreach (var (label, url) in sources)
            sb.AppendLine($"- {label}: {url}");

        return sb.ToString();
    }

    private static IEnumerable<string> Sections(ComuneInfo comune, bool isGuide) =>
        isGuide
            ?
            [
                "CIN (Codice Identificativo Nazionale)",
                "Comunicazione degli ospiti alla Questura (Alloggiati Web)",
                $"Imposta di soggiorno a {comune.Name}",
                "Fonti ufficiali",
            ]
            :
            [
                $"Imposta di soggiorno a {comune.Name}",
                "Come si calcola",
                "Esenzioni e riduzioni",
                "Fonti ufficiali",
            ];

    private static void AppendTouristTax(StringBuilder sb, ComuneInfo comune, IReadOnlyList<TouristTaxRate> taxRates)
    {
        if (taxRates.Count == 0)
        {
            sb.AppendLine($"- Imposta di soggiorno: CasaZen non ha una tariffa verificata per {comune.Name}. " +
                          "Non indicare importi: rimanda al sito del comune.");
            return;
        }

        sb.AppendLine($"- Imposta di soggiorno: la stabilisce il comune di {comune.Name}. Tariffe in vigore oggi:");
        foreach (var rate in taxRates)
        {
            var amount = rate.CalculationMethod == TouristTaxCalculationMethod.PercentOfNightlyPrice
                ? $"{Number(rate.PercentOfNightlyPrice)}% del prezzo della notte a persona" +
                  (rate.CapPerPersonPerNight is { } cap ? $", al massimo {Euro(cap)} a persona per notte" : string.Empty)
                : $"{Euro(rate.RatePerPersonPerNight)} a persona per notte";
            var details = new List<string> { amount };
            if (!string.IsNullOrWhiteSpace(rate.AccommodationCategory))
                details.Add($"categoria: {rate.AccommodationCategory}");
            if (rate.SeasonStart is not null)
                details.Add($"stagione dal {rate.SeasonStart} al {rate.SeasonEnd}");
            details.Add(rate.MaxNights is { } maxNights
                ? $"si paga per le prime {maxNights} notti"
                : "nessun limite di notti indicato");
            details.Add(rate.MinimumAge > 0
                ? $"esenti gli ospiti sotto i {rate.MinimumAge} anni"
                : "nessuna esenzione per età indicata");
            if (rate.ReducedRateMaxAge is { } reducedAge && rate.ReducedRatePerPersonPerNight is { } reduced)
                details.Add($"tariffa ridotta di {Euro(reduced)} fino a {reducedAge} anni compresi");
            details.Add($"in vigore dal {rate.EffectiveFrom.ToString("d MMMM yyyy", Italian)}");
            sb.AppendLine($"  - {string.Join("; ", details)}");
        }
    }

    private static IEnumerable<(string Label, string Url)> Sources(bool isGuide, IReadOnlyList<TouristTaxRate> taxRates)
    {
        var sources = isGuide ? ComplianceSources.ToList() : [];
        foreach (var url in taxRates
                     .Select(r => r.SourceUrl?.Trim())
                     .Where(u => Uri.TryCreate(u, UriKind.Absolute, out var uri) && uri.Scheme == Uri.UriSchemeHttps)
                     .Distinct(StringComparer.OrdinalIgnoreCase))
        {
            sources.Add(("Tariffe dell'imposta di soggiorno pubblicate dal comune", url!));
        }

        return sources;
    }

    private static string Euro(decimal amount) => $"€ {amount.ToString("N2", Italian)}";

    private static string Number(decimal? value) => value?.ToString("0.##", Italian) ?? "?";
}
