using Casazen.Core.Entities;
using Casazen.Core.Services;
using Casazen.Infrastructure.Services;
using Casazen.Web.DTOs;
using Casazen.Web.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Casazen.Web.Controllers;

[ApiController]
[Route("api/tourist-tax-rates")]
[Authorize]
public class TouristTaxRatesController(
    ITouristTaxService touristTaxService,
    ILogger<TouristTaxRatesController> logger) : ControllerBase
{
    /// <summary>
    /// Get all active tourist tax rates
    /// </summary>
    [HttpGet]
    public async Task<ActionResult<IEnumerable<TouristTaxRate>>> GetAll()
    {
        var rates = await touristTaxService.GetAllTaxRatesAsync();
        return Ok(rates);
    }

    /// <summary>
    /// Get tourist tax rate by ID
    /// </summary>
    [HttpGet("{id:guid}")]
    public async Task<ActionResult<TouristTaxRate>> GetById(Guid id)
    {
        var rate = await touristTaxService.GetTaxRateByIdAsync(id);

        if (rate == null)
        {
            logger.LogWarning("Tourist tax rate not found: {Id}", id);
            return this.ApiProblem(
                StatusCodes.Status404NotFound,
                TouristTaxService.TouristTaxRateNotFoundCode,
                "TouristTaxRateNotFound");
        }

        return Ok(rate);
    }

    /// <summary>
    /// Get active tax rate for a specific city
    /// </summary>
    [HttpGet("city/{city}")]
    public async Task<ActionResult<TouristTaxRate>> GetByCity(string city, [FromQuery] DateTime? date = null)
    {
        var effectiveDate = date ?? DateTime.UtcNow;
        var rate = await touristTaxService.GetTaxRateAsync(city, effectiveDate);

        if (rate == null)
            return NotFound($"No tax rate found for city: {city}");

        return Ok(rate);
    }

    /// <summary>
    /// Calculate tourist tax for a booking
    /// </summary>
    [HttpPost("calculate")]
    public async Task<ActionResult<TouristTaxCalculationResponse>> Calculate(
        [FromBody] TouristTaxCalculationRequest request)
    {
        try
        {
            var taxAmount = await touristTaxService.CalculateTouristTaxAsync(
                request.City,
                request.NumberOfAdults,
                request.NumberOfChildren,
                request.CheckInDate,
                request.CheckOutDate);

            var nights = (request.CheckOutDate.Date - request.CheckInDate.Date).Days;

            return Ok(new TouristTaxCalculationResponse
            {
                City = request.City,
                TaxAmount = taxAmount,
                NumberOfAdults = request.NumberOfAdults,
                NumberOfChildren = request.NumberOfChildren,
                Nights = nights,
                CheckInDate = request.CheckInDate,
                CheckOutDate = request.CheckOutDate
            });
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Error calculating tourist tax for city {City}", request.City);
            return BadRequest(new { error = ex.Message });
        }
    }

    /// <summary>
    /// Create a tourist tax rate (Admin only). The id is generated by the server.
    /// </summary>
    [HttpPost]
    [Authorize(Policy = "AdminOnly")]
    [ProducesResponseType(typeof(TouristTaxRate), StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<TouristTaxRate>> Create(
        [FromBody] TouristTaxRateRequest request,
        CancellationToken cancellationToken)
    {
        var result = await touristTaxService.CreateTaxRateAsync(request.ToInput(), cancellationToken);
        logger.LogInformation(
            "Tourist tax rate {Id} created for city {City}: {Rate}/person/night",
            result.Id, result.City, result.RatePerPersonPerNight);

        return CreatedAtAction(nameof(GetById), new { id = result.Id }, result);
    }

    /// <summary>
    /// Update tourist tax rate by ID (Admin only). 404 when the id does not exist.
    /// </summary>
    [HttpPut("{id:guid}")]
    [Authorize(Policy = "AdminOnly")]
    [ProducesResponseType(typeof(TouristTaxRate), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<TouristTaxRate>> Update(
        Guid id,
        [FromBody] TouristTaxRateRequest request,
        CancellationToken cancellationToken)
    {
        var result = await touristTaxService.UpdateTaxRateAsync(id, request.ToInput(), cancellationToken);
        logger.LogInformation(
            "Tourist tax rate {Id} updated for city {City}: {Rate}/person/night",
            id, result.City, result.RatePerPersonPerNight);

        return Ok(result);
    }

    /// <summary>
    /// Delete tourist tax rate by ID (Admin only): soft delete, the rate stays in history as inactive.
    /// </summary>
    [HttpDelete("{id:guid}")]
    [Authorize(Policy = "AdminOnly")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Delete(Guid id, CancellationToken cancellationToken)
    {
        await touristTaxService.DeactivateTaxRateAsync(id, cancellationToken);
        logger.LogInformation("Tourist tax rate soft-deleted: {Id}", id);
        return NoContent();
    }
}

public record TouristTaxCalculationRequest(
    string City,
    int NumberOfAdults,
    int NumberOfChildren,
    DateTime CheckInDate,
    DateTime CheckOutDate);

public record TouristTaxCalculationResponse
{
    public string City { get; init; } = string.Empty;
    public decimal TaxAmount { get; init; }
    public int NumberOfAdults { get; init; }
    public int NumberOfChildren { get; init; }
    public int Nights { get; init; }
    public DateTime CheckInDate { get; init; }
    public DateTime CheckOutDate { get; init; }
}
