using System.Diagnostics;
using Casazen.Web.Resources;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Localization;

namespace Casazen.Web.Infrastructure;

/// <summary>
/// The single shape of every API error: RFC 7807 ProblemDetails (<c>application/problem+json</c>) with
/// <list type="bullet">
/// <item><c>code</c>: stable snake_case identifier the frontend can branch on and translate (<see cref="ProblemCodes"/>);</item>
/// <item><c>title</c> / <c>detail</c>: localized from <c>Resources/SharedResources*.resx</c>
/// (Italian by default, English with <c>Accept-Language: en</c>), never an internal exception message;</item>
/// <item><c>traceId</c>: the id logged with the error, to correlate a response with server logs;</item>
/// <item><c>errors</c>: field → messages, only on validation problems.</item>
/// </list>
/// Applied by <see cref="Middleware.ErrorHandlingMiddleware"/> (exceptions and empty error responses), by
/// <c>AddProblemDetails</c> (problems generated by the framework: model validation, <c>NotFound()</c>,
/// <c>ValidationProblem()</c>...) and by <see cref="ApiProblemControllerExtensions.ApiProblem"/>.
/// </summary>
public static class ApiProblemDetails
{
    public const string ContentType = "application/problem+json";
    public const string CodeExtension = "code";
    public const string TraceIdExtension = "traceId";

    // English titles set by ASP.NET Core defaults; replaced by the localized title.
    private const string FrameworkValidationTitle = "One or more validation errors occurred.";
    private const string FrameworkServerErrorTitle = "An error occurred while processing your request.";

    // No generic detail: the client shows the field "errors" when "detail" is empty.
    private static readonly StatusTexts ValidationTexts = new(
        "ValidationError", null, "https://tools.ietf.org/html/rfc9110#section-15.5.1");

    private static readonly Dictionary<int, StatusTexts> TextsByStatus = new()
    {
        [StatusCodes.Status400BadRequest] = new("BadRequest", "BadRequestDetail", "https://tools.ietf.org/html/rfc9110#section-15.5.1"),
        [StatusCodes.Status401Unauthorized] = new("Unauthorized", "UnauthorizedDetail", "https://tools.ietf.org/html/rfc9110#section-15.5.2"),
        [StatusCodes.Status403Forbidden] = new("Forbidden", "ForbiddenDetail", "https://tools.ietf.org/html/rfc9110#section-15.5.4"),
        [StatusCodes.Status404NotFound] = new("NotFound", "NotFoundDetail", "https://tools.ietf.org/html/rfc9110#section-15.5.5"),
        [StatusCodes.Status409Conflict] = new("Conflict", "ConflictDetail", "https://tools.ietf.org/html/rfc9110#section-15.5.10"),
        [StatusCodes.Status422UnprocessableEntity] = new("BusinessRuleViolation", "BusinessRuleViolationDetail", "https://tools.ietf.org/html/rfc9110#section-15.5.21"),
        [StatusCodes.Status429TooManyRequests] = new("TooManyRequests", "TooManyRequestsDetail", "https://tools.ietf.org/html/rfc6585#section-4"),
        [StatusCodes.Status500InternalServerError] = new("InternalServerError", "InternalServerErrorDetail", "https://tools.ietf.org/html/rfc9110#section-15.6.1"),
        [StatusCodes.Status503ServiceUnavailable] = new("ServiceUnavailable", "ServiceUnavailableDetail", "https://tools.ietf.org/html/rfc9110#section-15.6.4"),
    };

    private static readonly StatusTexts OtherClientErrorTexts = new("RequestFailed", "RequestFailedDetail", null);
    private static readonly StatusTexts OtherServerErrorTexts = new("InternalServerError", "InternalServerErrorDetail", null);

    /// <summary>Trace id written in the response and in the error log.</summary>
    public static string GetTraceId(HttpContext httpContext) => Activity.Current?.Id ?? httpContext.TraceIdentifier;

    /// <summary>
    /// Builds a complete problem for <paramref name="statusCode"/>. <paramref name="messageKey"/> is a resource key of
    /// <c>SharedResources</c> for the <c>detail</c>; when null (or missing from the resources) the generic message of the
    /// status is used, so a raw key never reaches the client.
    /// </summary>
    public static ProblemDetails Create(
        HttpContext httpContext,
        int statusCode,
        string? code = null,
        string? messageKey = null,
        IReadOnlyList<object>? messageArgs = null)
    {
        var problem = new ProblemDetails { Status = statusCode };
        if (!string.IsNullOrWhiteSpace(code))
            problem.Extensions[CodeExtension] = code;

        if (!string.IsNullOrWhiteSpace(messageKey))
        {
            var localized = GetLocalizer(httpContext)[messageKey, messageArgs?.ToArray() ?? []];
            if (!localized.ResourceNotFound)
                problem.Detail = localized.Value;
        }

        Complete(problem, httpContext);
        return problem;
    }

    /// <summary>
    /// Adds what every error response must carry and the framework does not set: <c>code</c> (from the status when
    /// missing), <c>traceId</c>, <c>instance</c>, a localized <c>title</c> in place of the English default and a
    /// localized generic <c>detail</c> when there is none. Validation problems keep an empty <c>detail</c> so the
    /// client shows their field <c>errors</c>.
    /// </summary>
    public static void Complete(ProblemDetails problem, HttpContext httpContext)
    {
        var status = problem.Status
            ?? (httpContext.Response.StatusCode >= 400 ? httpContext.Response.StatusCode : StatusCodes.Status500InternalServerError);
        problem.Status = status;

        var isValidation = problem is HttpValidationProblemDetails;
        var texts = isValidation ? ValidationTexts : GetTexts(status);
        var localizer = GetLocalizer(httpContext);

        if (!problem.Extensions.TryGetValue(CodeExtension, out var code) || code is not string { Length: > 0 })
            problem.Extensions[CodeExtension] = isValidation ? ProblemCodes.ValidationError : ProblemCodes.ForStatus(status);

        if (IsFrameworkDefaultTitle(problem.Title, status))
            problem.Title = localizer[texts.TitleKey].Value;

        if (texts.DetailKey is not null && string.IsNullOrWhiteSpace(problem.Detail))
            problem.Detail = localizer[texts.DetailKey].Value;

        problem.Type ??= texts.Type;
        problem.Instance ??= httpContext.Request.PathBase.Add(httpContext.Request.Path).Value;
        problem.Extensions[TraceIdExtension] = GetTraceId(httpContext);
    }

    private static StatusTexts GetTexts(int status) =>
        TextsByStatus.TryGetValue(status, out var texts)
            ? texts
            : status >= 500 ? OtherServerErrorTexts : OtherClientErrorTexts;

    private static bool IsFrameworkDefaultTitle(string? title, int status) =>
        string.IsNullOrWhiteSpace(title)
        || title == ReasonPhrases.GetReasonPhrase(status)
        || title == FrameworkValidationTitle
        || title == FrameworkServerErrorTitle;

    private static IStringLocalizer GetLocalizer(HttpContext httpContext) =>
        httpContext.RequestServices.GetRequiredService<IStringLocalizer<SharedResources>>();

    private sealed record StatusTexts(string TitleKey, string? DetailKey, string? Type);
}
