using System.Text.RegularExpressions;
using UglyToad.PdfPig;
using UglyToad.PdfPig.Content;

namespace Casazen.Tests.Unit.Documents;

/// <summary>
/// Reads the PDFs generated by the application in tests (LT-09): text through the ToUnicode maps of the embedded
/// fonts (PdfPig, test-only dependency), page sizes, watermark, fonts.
/// </summary>
internal static partial class PdfTestReader
{
    /// <summary>Words below this height (points from the bottom edge) are in the footer ("Pagina N di M").</summary>
    private const double FooterTop = 60;

    /// <summary>Letters at least this large are the watermark; the body uses at most 15 pt.</summary>
    private const double WatermarkMinSize = 40;

    /// <summary>Every word of every page (body, footer, watermark), separated by one space.</summary>
    public static string Text(byte[] pdf)
    {
        using var document = PdfDocument.Open(pdf);
        return string.Join(' ', document.GetPages().SelectMany(p => p.GetWords()).Select(w => w.Text));
    }

    /// <summary>Words of the body of every page, in reading order: no footer, no watermark.</summary>
    public static IReadOnlyList<string> BodyWords(byte[] pdf)
    {
        using var document = PdfDocument.Open(pdf);
        return document.GetPages()
            .SelectMany(p => p.GetWords())
            .Where(w => w.BoundingBox.Bottom > FooterTop && !IsWatermark(w))
            .Select(w => w.Text)
            .ToList();
    }

    public static IReadOnlyList<PdfTestPage> Pages(byte[] pdf)
    {
        using var document = PdfDocument.Open(pdf);
        return document.GetPages().Select(p =>
        {
            // The watermark is rotated: the word extractor reorders its letters, the content stream keeps them in order.
            return new PdfTestPage(
                p.Width,
                p.Height,
                string.Join(' ', p.GetWords().Where(w => !IsWatermark(w)).Select(w => w.Text)),
                string.Concat(p.Letters.Where(l => l.PointSize >= WatermarkMinSize).Select(l => l.Value)));
        }).ToList();
    }

    /// <summary>Rightmost point reached by the text (watermark excluded), in points from the left edge.</summary>
    public static double MaxTextRight(byte[] pdf)
    {
        using var document = PdfDocument.Open(pdf);
        return document.GetPages()
            .SelectMany(p => p.Letters)
            .Where(l => l.PointSize < WatermarkMinSize && !string.IsNullOrWhiteSpace(l.Value))
            .Max(l => l.BoundingBox.Right);
    }

    /// <summary>Base names of the fonts the PDF references, without the subset prefix (<c>#20</c> decoded).</summary>
    public static IReadOnlyList<string> FontNames(byte[] pdf) =>
        BaseFontPattern().Matches(Latin1(pdf))
            .Select(m => m.Groups[1].Value.Replace("#20", " ", StringComparison.Ordinal))
            .Distinct(StringComparer.Ordinal)
            .ToList();

    /// <summary>Font descriptors and embedded TrueType programs (FontFile2) in the PDF.</summary>
    public static (int Descriptors, int EmbeddedPrograms) FontEmbedding(byte[] pdf)
    {
        var raw = Latin1(pdf);
        return (FontDescriptorPattern().Count(raw), FontFile2Pattern().Count(raw));
    }

    private static bool IsWatermark(Word word) => word.Letters.Count > 0 && word.Letters.All(l => l.PointSize >= WatermarkMinSize);

    private static string Latin1(byte[] pdf) => System.Text.Encoding.Latin1.GetString(pdf);

    [GeneratedRegex(@"/BaseFont\s*/(?:[A-Z]{6}\+)?([^\s/<>\[\]()]+)")]
    private static partial Regex BaseFontPattern();

    [GeneratedRegex(@"/Type\s*/FontDescriptor\b")]
    private static partial Regex FontDescriptorPattern();

    [GeneratedRegex(@"/FontFile2\s")]
    private static partial Regex FontFile2Pattern();
}

internal sealed record PdfTestPage(double Width, double Height, string Text, string Watermark);
